### ISSUE TITLE
[fix]: 챌린지 삭제 오류 수정

### ISSUE THREAD

**Issue by jihyun0v0** [Team-HMH/HMH-Android#156]
## 기능 추가
- 챌린지 삭제 시도시 최상단 두 앱이 삭제가 안되는 오류 수정

## 작업 상세 내용
- [ ] 오류 원인 파악
- [ ] 오류 수정

**Comment by KwakEuiJin** [comment]
건드시는 파일들 전체적인 리팩터링도 부탁드려요
