### ISSUE TITLE
[fix]: 컨벤션 수정

### ISSUE THREAD

**Issue by KwakEuiJin** [Team-HMH/HMH-Android#68]
<img width="763" alt="image" src="https://github.com/Team-HMH/HMH-Android/assets/93872496/807f628c-b985-400a-9659-2317066ad153">

**Comment by KwakEuiJin** [comment]
컨벤션 변경으로 앞으로 개발하실 때 차근차근 where의 사용을 제외하여 코드 처리 부탁드립니다.

**Comment by kangyuri1114** [comment]
확인했습니다!
